// ui/react/apps/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import "./react-calendar-web";
  import calendarData from "./data/calendar-data.json";

  type CalendarDataItem = {
    title: string;
    start: string;
    end: string;
    allDay?: boolean;
  };

  type ReactCalendarElement = HTMLElement & {
    data: CalendarDataItem[];
    title: string;
    height: number | string;
    width: number | string;
  };

  let calendarElement: ReactCalendarElement | null = null;

  onMount(() => {
    if (!calendarElement) {
      return;
    }

    calendarElement.data = calendarData;
    calendarElement.title = "Svelte Project Calendar";
    calendarElement.height = 620;
    calendarElement.width = "100%";
  });
</script>

<main class="page">
  <h1>Svelte Host for React Web Component</h1>
  <p>The calendar below is rendered by the React-generated &lt;react-calendar&gt; web component.</p>
  <react-calendar bind:this={calendarElement}></react-calendar>
</main>

// ui/react/apps/web/src/App.tsx
import { useEffect, useRef } from "react";
import type { ReactCalendarHTMLElement } from "./custom-elements";
import calendarData from "./data/calendar-data.json";
import "./react-calendar-element";

const App = () => {
  const calendarRef = useRef<ReactCalendarHTMLElement | null>(null);

  useEffect(() => {
    if (!calendarRef.current) {
      return;
    }

    calendarRef.current.data = calendarData;
    calendarRef.current.title = "Team Delivery Calendar";
    calendarRef.current.height = 620;
    calendarRef.current.width = "100%";
  }, []);

  return (
    <main className="page">
      <h1>React Calendar Web Component</h1>
      <p>
        This reusable web component is rendered as {"<react-calendar>"} and
        receives data, title, height, and width as properties.
      </p>
      <react-calendar ref={calendarRef} />
    </main>
  );
};

export default App;
